<?php
$callable = fn() => throw new Exception();
